base: fix unused variable warning
Error while processing /home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/90/execroot/_main/src/v/base/vassert.h.
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/90/execroot/_main/src/v/base/vassert.h:24:20: error: unused variable 'g_assert_log' [clang-diagnostic-unused-variable]
   24 | static dummyassert g_assert_log;

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>