k/protocol: move kafka_request_schemata into v::kafka_protocol
in this change,

* `v::kafka_request_schemata` is merged into `v::kafka_protocol`, per Noah,
  > early on it wasn't clear how these libraries might grow independently.
  > we are far enough along now that it doesn't seem like they are going
  > to grow independently.
* the rule to generate message C++ binding is lifted into
  src/v/kafka/protocol/CMakeLists.txt, because per CMake document
  add_custom_command()
  > defines a command to generate specified OUTPUT file(s). A target created
  > in the same directory (CMakeLists.txt file) that specifies any output of
  > the custom command as a source file is given a rule to generate the file
  > using the command at build time.

  so we should keep both the `add_custom_command()` call and the target
  which references the generated file in the same CMakeLists.txt file.

so it'd be simpler if we can merge them into a single target.

also, in sasl_authenticate_response.cc,
operator<<(.., const sasl_authenticate_response_data&) references
operator<<(.., kafka::error_code). the former is compiled as a part of
v::kafka_request_schemata. while the latter is defined by
kafka/protocol/errors.cc. which is in turn compiled as a part of
v::kafka_protocol. so we need to help v::kafka_request_schemata
to link against v::kafka_protocol to avoid following link failure:

lib/libv_v_kafka_request_schemata.a(sasl_authenticate_response.cc.o): in function `void fmt::v8::detail::format_value<char, kafka::error_code>(fmt::v8::detail::buffer<char>&, kafka::error_code const&, fmt::v8::detail::locale_ref)':
sasl_authenticate_response.cc:(.text._ZN3fmt2v86detail12format_valueIcN5kafka10error_codeEEEvRNS1_6bufferIT_EERKT0_NS1_10locale_refE[_ZN3fmt2v86detail12format_valueIcN5kafka10error_codeEEEvRNS1_6bufferIT_EERKT0_NS1_10locale_refE]+0x551): undefined reference to `kafka::operator<<(std::ostream&, kafka::error_code)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Signed-off-by: Kefu Chai <tchaikov@gmail.com>