cloud_io: fix unused variable warning
Error while processing /home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1285/execroot/_main/src/v/cloud_io/auth_refresh_bg_op.h.
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1285/execroot/_main/src/v/cloud_io/auth_refresh_bg_op.h:23:31: error: unused variable 'auth_refresh_shard_id' [clang-diagnostic-unused-const-variable]
   23 | static constexpr ss::shard_id auth_refresh_shard_id = 0;

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>