rpk: print errors in configChecker failure
ConfigFileChecker was ignoring the error, the
user will get only :

 Error: System check 'Config file valid' failed.
 Required: true, Current false

With this change we are now appending the errors.