Update kubernetes-external-connect.md
Using this command
```
--node-ami auto
```
gives an error
```
Error: invalid AMI "auto" (managedNodeGroups[0].ami)
```

According to [this](https://githubmemory.com/repo/weaveworks/eksctl/issues/4039), this part is no longer required, since auto is the default value.