syschecks: fix unused function warning
Error while processing /home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1727/execroot/_main/src/v/syschecks/syschecks.h.
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1727/execroot/_main/src/v/syschecks/syschecks.h:31:20: error: unused function 'initialize_intrinsics' [clang-diagnostic-unused-function]
   31 | static inline void initialize_intrinsics() {
      |                    ^~~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1727/execroot/_main/src/v/syschecks/syschecks.h:43:20: error: unused function 'cpu' [clang-diagnostic-unused-function]
   43 | static inline void cpu() {

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>