iceberg: account for snapshot summary metrics
Certain query engines (e.g. Redshift) require some optional metrics[1] to
be set in our snapshot summaries. It isn't clear exactly which all
metrics are actually required, but at the very least, Redshift will
complain about a missing "total-records" field.

This commit updates the merge append action to do accounting for some of
these metrics (num records, num data files, size).

There are "added" metrics which account for just what is added in the
given snapshot, and "total" metrics, which account for the whole
snapshot. The spec includes "deleted" metrics, but as Redpanda doesn't
delete anything, we are omitting them for now.

"Total" metrics will be omitted if the previous snapshot was missing the
metric, following the Python[2] and Java[3] implementations.

I tested this manually against Redshift. Without this change, we would
see errors like:

```
ERROR: ----------------------------------------------- error: Error parsing table metadata. code: 15003 context: Required field total-records missing. query: 409612[child_sequence:1] location: json_utils.hpp:56 process: padbmaster [pid=1073848668] ----------------------------------------------- [ErrorId: 1-68b0b26f-4870c0806c81008553e63bc0]
```

[1] https://iceberg.apache.org/spec/#metrics
[2] https://github.com/apache/iceberg-python/blob/06b9467f1db2b71c51d4c1be5f3a5144afa52880/pyiceberg/table/snapshots.py#L370-L392
[3] https://github.com/apache/iceberg/blob/2b66fc553acc0e7ddc9edcdb26095daf4e8a04c2/core/src/main/java/org/apache/iceberg/SnapshotProducer.java#L341-L411

(cherry picked from commit cf9f2bde8867223bab81e44bdabf27c12ef61661)