storage: fix missing definition
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/external/toolchains_llvm~~llvm~llvm_18_toolchain_llvm/bin/../include/c++/v1/__type_traits/is_base_of.h:26:59: error: incomplete type 'storage::segment' used in type trait expression [clang-diagnostic-error]
   26 | inline constexpr bool is_base_of_v = __is_base_of(_Bp, _Dp);
      |                                                           ^
external/_main~non_module_dependencies~seastar/include/seastar/core/shared_ptr.hh:241:15: note: in instantiation of variable template specialization 'std::is_base_of_v<seastar::enable_lw_shared_from_this<storage::segment>, storage::segment>' requested here
  241 |          std::is_base_of_v<enable_lw_shared_from_this<T>, T>,
      |               ^
external/_main~non_module_dependencies~seastar/include/seastar/core/shared_ptr.hh:324:13: note: in instantiation of template class 'seastar::internal::lw_shared_ptr_accessors<storage::segment>' requested here
  324 |             accessors<T>::dispose(_p);
      |             ^
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/external/toolchains_llvm~~llvm~llvm_18_toolchain_llvm/bin/../include/c++/v1/__memory/construct_at.h:67:11: note: in instantiation of member function 'seastar::lw_shared_ptr<storage::segment>::~lw_shared_ptr' requested here
   67 |   __loc->~_Tp();
      |           ^
bazel-out/k8-fastbuild/bin/src/v/storage/_virtual_includes/storage/storage/segment_set.h:54:5: note: in instantiation of member function 'seastar::circular_buffer<seastar::lw_shared_ptr<storage::segment>>::~circular_buffer' requested here
   54 |     segment_set(segment_set&&) noexcept = default;

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>