tools: Fix uv ruff version string
Needs `==` and not `=`.

Otherwise getting:

```
stephan@rp:/build/redpanda$ ./tools/format-py
/build/redpanda /build/redpanda
error: Failed to parse: `ruff=0.12.10`
  Caused by: no such comparison operator "=", must be one of ~= == != <= >= < > ===
ruff=0.12.10
    ^^^^^^^^
/build/redpanda
```

(cherry picked from commit 3d6b4ba9e1f10078bb8ec23194761258d680ead7)