test: disable leadership balancing in test
It seems that leadership rebalancing was causing some of the rpk
operations to be a bit flaky. There may be an opportunity here to add
some retrying into rpk/franz-go.

rptest.clients.rpk.RpkException: RpkException<command
/var/lib/buildkite-agent/builds/buildkite-amd64-builders-i-07ad15334ccea297e-1/vectorized/redpanda/vbuild/debug/clang/dist/local/redpanda/bin/rpk
group --brokers docker_n_14:9092,docker_n_6:9092,docker_n_5:9092 seek g2
--to start returned 1, output: , error: unable to list all offsets
successfully: NOT_LEADER_FOR_PARTITION: This server is not the leader
for that topic-partition.

Fixes: #3443

Signed-off-by: Noah Watkins <noah@vectorized.io>