test: retry on readyReplicas test
Presumably if the cluster isn't yet fully initialized then jsonpath
query for readyReplicas will return an empty string and converting that
to an integer will fail. The entire process is in a wait_until, so we'll
just ignore these errors.

    test_id:    HighThroughputTest.test_add_and_decommission
    status:     FAIL
    run time:   2629.113 seconds

    ValueError("invalid literal for int() with base 10: ''")
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/ducktape/tests/runner_client.py", line 184, in _do_run
        data = self.run_test()
      File "/usr/local/lib/python3.10/dist-packages/ducktape/tests/runner_client.py", line 269, in run_test
        return self.test_context.function(self.test)
      File "/home/ubuntu/redpanda/tests/rptest/services/cluster.py", line 104, in wrapped
        r = f(self, *args, **kwargs)
      File "/home/ubuntu/redpanda/tests/rptest/redpanda_cloud_tests/high_throughput_test.py", line 1221, in test_add_and_decommission
        self._stage_add_and_decommission()
      File "/home/ubuntu/redpanda/tests/rptest/redpanda_cloud_tests/high_throughput_test.py", line 1251, in _stage_add_and_decommission
        self._patch_cluster_replicas(cluster_name, orig_replicas)
      File "/home/ubuntu/redpanda/tests/rptest/redpanda_cloud_tests/high_throughput_test.py", line 1165, in _patch_cluster_replicas
        wait_until(
      File "/usr/local/lib/python3.10/dist-packages/ducktape/utils/util.py", line 53, in wait_until
        raise e
      File "/usr/local/lib/python3.10/dist-packages/ducktape/utils/util.py", line 44, in wait_until
        if condition():
      File "/home/ubuntu/redpanda/tests/rptest/redpanda_cloud_tests/high_throughput_test.py", line 1166, in <lambda>
        lambda: cluster_ready_replicas(cluster_name) == replicas,
      File "/home/ubuntu/redpanda/tests/rptest/redpanda_cloud_tests/high_throughput_test.py", line 1144, in cluster_ready_replicas
        return int(
    ValueError: invalid literal for int() with base 10: ''

Fixes: https://github.com/redpanda-data/redpanda/issues/16631

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>