kafka: fix unused variable,function warning
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/2505/execroot/_main/src/v/kafka/protocol/kafka_batch_adapter.h:25:18: error: unused variable 'kafka_header_size' [clang-diagnostic-unused-const-variable]
   25 | constexpr size_t kafka_header_size = sizeof(int64_t) + // base offset

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/8764/execroot/_main/src/v/kafka/protocol/types.h:134:30: error: unused variable 'never_flexible' [clang-diagnostic-unused-const-variable]
  134 | static constexpr api_version never_flexible = api_version(-1);

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/281/execroot/_main/src/v/kafka/client/brokers.h:29:22: error: unused variable 'unknown_node_id' [clang-diagnostic-unused-const-variable]
   29 | const model::node_id unknown_node_id{-1};

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:40:35: error: unused variable 'topic_property_compaction_strategy' [clang-diagnostic-unused-const-variable]
   40 | static constexpr std::string_view topic_property_compaction_strategy

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:42:35: error: unused variable 'topic_property_timestamp_type' [clang-diagnostic-unused-const-variable]
   42 | static constexpr std::string_view topic_property_timestamp_type

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:44:35: error: unused variable 'topic_property_segment_size' [clang-diagnostic-unused-const-variable]
   44 | static constexpr std::string_view topic_property_segment_size = "segment.bytes";

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:45:35: error: unused variable 'topic_property_max_message_bytes' [clang-diagnostic-unused-const-variable]
   45 | static constexpr std::string_view topic_property_max_message_bytes

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:47:35: error: unused variable 'topic_property_recovery' [clang-diagnostic-unused-const-variable]
   47 | static constexpr std::string_view topic_property_recovery

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:49:35: error: unused variable 'topic_property_remote_write' [clang-diagnostic-unused-const-variable]
   49 | static constexpr std::string_view topic_property_remote_write

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:51:35: error: unused variable 'topic_property_remote_read' [clang-diagnostic-unused-const-variable]
   51 | static constexpr std::string_view topic_property_remote_read

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:53:35: error: unused variable 'topic_property_read_replica' [clang-diagnostic-unused-const-variable]
   53 | static constexpr std::string_view topic_property_read_replica

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:55:35: error: unused variable 'topic_property_replication_factor' [clang-diagnostic-unused-const-variable]
   55 | static constexpr std::string_view topic_property_replication_factor

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:57:35: error: unused variable 'topic_property_remote_delete' [clang-diagnostic-unused-const-variable]
   57 | static constexpr std::string_view topic_property_remote_delete

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:59:35: error: unused variable 'topic_property_segment_ms' [clang-diagnostic-unused-const-variable]
   59 | static constexpr std::string_view topic_property_segment_ms = "segment.ms";

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:60:35: error: unused variable 'topic_property_write_caching' [clang-diagnostic-unused-const-variable]
   60 | static constexpr std::string_view topic_property_write_caching

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:63:35: error: unused variable 'topic_property_flush_ms' [clang-diagnostic-unused-const-variable]
   63 | static constexpr std::string_view topic_property_flush_ms = "flush.ms";

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:64:35: error: unused variable 'topic_property_flush_bytes' [clang-diagnostic-unused-const-variable]
   64 | static constexpr std::string_view topic_property_flush_bytes = "flush.bytes";

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:67:35: error: unused variable 'topic_property_record_key_schema_id_validation' [clang-diagnostic-unused-const-variable]
   67 | static constexpr std::string_view topic_property_record_key_schema_id_validation

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:70:3: error: unused variable 'topic_property_record_key_subject_name_strategy' [clang-diagnostic-unused-const-variable]
   70 |   topic_property_record_key_subject_name_strategy

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:73:3: error: unused variable 'topic_property_record_value_schema_id_validation' [clang-diagnostic-unused-const-variable]
   73 |   topic_property_record_value_schema_id_validation

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:76:3: error: unused variable 'topic_property_record_value_subject_name_strategy' [clang-diagnostic-unused-const-variable]
   76 |   topic_property_record_value_subject_name_strategy

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1735/execroot/_main/src/v/kafka/server/handlers/topics/types.h:81:3: error: unused variable 'topic_property_record_key_schema_id_validation_compat' [clang-diagnostic-unused-const-variable]
   81 |   topic_property_record_key_schema_id_validation_compat

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/2694/execroot/_main/src/v/kafka/server/handlers/topics/types.h:84:3: error: unused variable 'topic_property_record_key_subject_name_strategy_compat' [clang-diagnostic-unused-const-variable]
   84 |   topic_property_record_key_subject_name_strategy_compat

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/2694/execroot/_main/src/v/kafka/server/handlers/topics/types.h:87:3: error: unused variable 'topic_property_record_value_schema_id_validation_compat' [clang-diagnostic-unused-const-variable]
   87 |   topic_property_record_value_schema_id_validation_compat

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/2694/execroot/_main/src/v/kafka/server/handlers/topics/types.h:90:3: error: unused variable 'topic_property_record_value_subject_name_strategy_compat' [clang-diagnostic-unused-const-variable]
   90 |   topic_property_record_value_subject_name_strategy_compat

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/2694/execroot/_main/src/v/kafka/server/handlers/topics/types.h:93:35: error: unused variable 'topic_property_mpx_virtual_cluster_id' [clang-diagnostic-unused-const-variable]
   93 | static constexpr std::string_view topic_property_mpx_virtual_cluster_id

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/2694/execroot/_main/src/v/kafka/server/handlers/topics/types.h:96:35: error: unused variable 'topic_property_iceberg_enabled' [clang-diagnostic-unused-const-variable]
   96 | static constexpr std::string_view topic_property_iceberg_enabled

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/2694/execroot/_main/src/v/kafka/server/handlers/topics/types.h:99:35: error: unused variable 'topic_property_leaders_preference' [clang-diagnostic-unused-const-variable]
   99 | static constexpr std::string_view topic_property_leaders_preference

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/2694/execroot/_main/src/v/kafka/server/handlers/topics/types.h:104:51: error: unused variable 'allowlist_topic_noop_confs' [clang-diagnostic-unused-const-variable]
  104 | static constexpr std::array<std::string_view, 20> allowlist_topic_noop_confs = {

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>

kafka: fix unused variable warning

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/3286/execroot/_main/src/v/kafka/server/request_context.h:59:16: error: unused variable 'request_header_size' [clang-diagnostic-unused-const-variable]
   59 | constexpr auto request_header_size = sizeof(int16_t) + sizeof(int16_t)

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>