cloud_roles: fix unused variable warnings
Error while processing /home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/320/execroot/_main/src/v/cloud_roles/types.h.
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/320/execroot/_main/src/v/cloud_roles/types.h:26:23: error: unused variable 'retryable_system_error_codes' [clang-diagnostic-unused-const-variable]
   26 | static constexpr auto retryable_system_error_codes = std::to_array(
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/320/execroot/_main/src/v/cloud_roles/types.h:31:23: error: unused variable 'retryable_http_status' [clang-diagnostic-unused-const-variable]
   31 | static constexpr auto retryable_http_status = std::to_array({
      |                       ^~~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/320/execroot/_main/src/v/cloud_roles/types.h:146:16: error: unused variable 'azure_storage_api_version' [clang-diagnostic-unused-const-variable]

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>