tests: wait for 'maintenance_mode' in rolling restart
We need to wait for `maintenance_mode` feature activation on all nodes for all
tests that undergo a rolling restart. This patch pulls in a wait to the
`rolling_restarter`, using the newly introduced `Admin.supports_feature()`
method that does just this.

Without this, we could see the following in tests:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ducktape/tests/runner_client.py", line 135, in run
    data = self.run_test()
  File "/usr/local/lib/python3.10/dist-packages/ducktape/tests/runner_client.py", line 227, in run_test
    return self.test_context.function(self.test)
  File "/usr/local/lib/python3.10/dist-packages/ducktape/mark/_mark.py", line 476, in wrapper
    return functools.partial(f, *args, **kwargs)(*w_args, **w_kwargs)
  File "/root/tests/rptest/services/cluster.py", line 35, in wrapped
    r = f(self, *args, **kwargs)
  File "/root/tests/rptest/tests/upgrade_test.py", line 234, in test_upgrade_with_all_workloads
    self.redpanda.rolling_restart_nodes(self.redpanda.nodes,
  File "/root/tests/rptest/services/redpanda.py", line 1634, in rolling_restart_nodes
    restarter.restart_nodes(nodes,
  File "/root/tests/rptest/services/rolling_restarter.py", line 74, in restart_nodes
    admin.maintenance_stop(node)
  File "/root/tests/rptest/services/admin.py", line 683, in maintenance_stop
    return self._request("delete", url)
  File "/root/tests/rptest/services/admin.py", line 334, in _request
    r.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://docker-rp-16:9644/v1/brokers/3/maintenance
```