topic_recovery: make schema validation errors log request
The error message isn't always very user-friendly, e.g.:

```
error: Cannot start topic recovery: bad recovery request payload: invalid request body: {"not":{"errorCode":25,"instanceRef":"#","schemaRef":"#"}}
```

With this commit, the body of the request is also logged.

(cherry picked from commit e0c5cb4db6e1be3f620d448f686daea740480792)