storage: adapt to non-copyable iterator
std::find_if requires copyable iterators, but
segment_meta_materializing_iterator is not copyable (contains a unique_ptr).
this is apparently not a problem in libc++ because it forwards the r-value
reference, but libstdc++ does make a copy.

    In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/algorithm:61:
    /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_algo.h:3923:29: error: call to deleted constructor of 'cloud_storage::segment_meta_materializing_iterator'
          return std::__find_if(__first, __last,
                                ^~~~~~~
    /home/nwatkins/src/redpanda-osbuild/src/v/archival/segment_reupload.cc:185:20: note: in instantiation of function template specialization 'std::find_if<cloud_storage::segment_meta_materializing_iterator, (lambda at /home/nwatkins/src/redpanda-osbuild/src/v/archival/segment_reupload.cc:186:48)>' requested here
             it = std::find_if(

Fix by adding a few hand-coded searches to replace calls to std::find_if.

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>