build: add missing #include <array>
When building in debug mode with shared libs I ran into:

[45/968] Building CXX object src/v/hashing/tests/CMakeFiles/xx_hashes_rpunit.dir/xx_tests.cc.o
FAILED: src/v/hashing/tests/CMakeFiles/xx_hashes_rpunit.dir/xx_tests.cc.o
/usr/bin/ccache /home/andrew/xfs/vbuild/llvm/install/bin/clang++ -DBOOST_TEST_DYN_LINK -DBOOST_TEST_NO_LIB -DXXH_PRIVATE_API -I/home/andrew/Repos/redpanda/src/v -I/home/andrew/xfs/vbuild/debug/clang/src/v -isystem /home/andrew/xfs/vbuild/debug/clang/rp_deps_install/include -fPIC -march=westmere -fuse-ld=lld -mllvm -inline-threshold=2500 -Wno-unused-lambda-capture -Wno-unused-command-line-argument -stdlib=libc++ -fsanitize=undefined -fsanitize=address -fstack-protector-strong -fno-plt -fstack-clash-protection -O0 -g -gdwarf-4 -gsplit-dwarf -fPIE -Wall -std=c++20 -MD -MT src/v/hashing/tests/CMakeFiles/xx_hashes_rpunit.dir/xx_tests.cc.o -MF src/v/hashing/tests/CMakeFiles/xx_hashes_rpunit.dir/xx_tests.cc.o.d -o src/v/hashing/tests/CMakeFiles/xx_hashes_rpunit.dir/xx_tests.cc.o -c /home/andrew/Repos/redpanda/src/v/hashing/tests/xx_tests.cc
/home/andrew/Repos/redpanda/src/v/hashing/tests/xx_tests.cc:29:24: error: implicit instantiation of undefined template 'std::array<int, 3>'
    std::array<int, 3> arr = {1, 2, 42};
                       ^
/home/andrew/xfs/vbuild/llvm/install/bin/../include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
/home/andrew/Repos/redpanda/src/v/hashing/tests/xx_tests.cc:41:24: error: implicit instantiation of undefined template 'std::array<int, 3>'
    std::array<int, 3> arr = {1, 2, 42};
                       ^
/home/andrew/xfs/vbuild/llvm/install/bin/../include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
2 errors generated.
[74/968] Building CXX object src/v/utils/CMakeFiles/v_utils.dir/request_auth.cc.o
ninja: build stopped: subcommand failed.
task: Failed to run task "rp:build": exit status 1