shadow_indexing_admin_api_test: fix undeclared variable
In a now corrected broken test case, the following exception was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ducktape/tests/runner_client.py", line 135, in run
    data = self.run_test()
  File "/usr/local/lib/python3.10/dist-packages/ducktape/tests/runner_client.py", line 227, in run_test
    return self.test_context.function(self.test)
  File "/root/tests/rptest/services/cluster.py", line 49, in wrapped
    r = f(self, *args, **kwargs)
  File "/root/tests/rptest/tests/shadow_indexing_admin_api_test.py", line 185, in test_topic_recovery_request_validation
    'bad_request'], f'unexpected status code: {response} for {payload}'
UnboundLocalError: local variable 'response' referenced before assignment

(cherry picked from commit 3c92dd1a0a9d63d33b170c23941e1952ecdac819)