cmake: install pex==2.1.100 not pex=2.1.00
as pip's requirement spec uses "==" for this purpose, see
https://pip.pypa.io/en/stable/reference/requirement-specifiers/#requirement-specifiers,
https://peps.python.org/pep-0508/ and
https://peps.python.org/pep-0440/#version-specifiers

otherwise we'd have:

FAILED: kafka-codegen-pex-prefix/src/kafka-codegen-pex-stamp/kafka-codegen-pex-install
cd /home/kefu/dev/redpanda/build/deps_build/kafka-codegen-pex-prefix/src/kafka-codegen-pex-build && /usr/bin/cmake -E chdir /home/kefu/dev/redpanda/build/deps_build/kafka-codegen-pex-prefix/src/kafka-codegen-pex py
thon3 -m venv env && /home/kefu/dev/redpanda/build/deps_build/kafka-codegen-pex-prefix/src/kafka-codegen-pex/env/bin/pip install pex=2.1.100 && /home/kefu/dev/redpanda/build/deps_build/kafka-codegen-pex-prefix/src/
kafka-codegen-pex/env/bin/pex jsonschema jinja2 -o /home/kefu/dev/redpanda/build/deps_install/bin/kafka-codegen-venv && /usr/bin/cmake -E touch /home/kefu/dev/redpanda/build/deps_build/kafka-codegen-pex-prefix/src/
kafka-codegen-pex-stamp/kafka-codegen-pex-install
ERROR: Invalid requirement: 'pex=2.1.100'
Hint: = is not a valid operator. Did you mean == ?

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
(cherry picked from commit 06300eb99209dab60bb001bb3e13d254b227c953)