model: fix unused variable,function warning
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1858/execroot/_main/src/v/model/timeout_clock.h:27:42: error: unused variable 'max_duration' [clang-diagnostic-unused-const-variable]
   27 | static constexpr timeout_clock::duration max_duration
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/7748/execroot/_main/src/v/model/fundamental.h:96:31: error: unused variable 'default_cluster_uuid' [clang-diagnostic-unused-const-variable]
   96 | static constexpr cluster_uuid default_cluster_uuid{};
      |                               ^~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/7748/execroot/_main/src/v/model/fundamental.h:105:19: error: unused variable 'unassigned_node_id' [clang-diagnostic-unused-const-variable]
  105 | constexpr node_id unassigned_node_id(-1);
      |                   ^~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/7748/execroot/_main/src/v/model/fundamental.h:294:32: error: unused variable 'invalid_lso' [clang-diagnostic-unused-const-variable]
  294 | static constexpr model::offset invalid_lso{next_offset(model::offset::min())};
      |                                ^~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/7748/execroot/_main/src/v/model/fundamental.h:429:41: error: unused variable 'current_control_record_version' [clang-diagnostic-unused-const-variable]
  429 | static constexpr control_record_version current_control_record_version{0};

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>

model: fix unused variable warning

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/8109/execroot/_main/src/v/model/record.h:614:36: error: unused variable 'no_pid' [clang-diagnostic-unused-const-variable]
  614 | static constexpr producer_identity no_pid{no_producer_id, no_producer_epoch};

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>