audit: fix unused function warnings
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1278/execroot/_main/src/v/security/audit/schemas/types.h:163:31: error: unused function 'ocsf_redpanda_metadata' [clang-diagnostic-unused-function]
  163 | static inline const metadata& ocsf_redpanda_metadata() {
      |                               ^~~~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1278/execroot/_main/src/v/security/audit/schemas/types.h:172:31: error: unused function 'ocsf_redpanda_metadata_cloud_profile' [clang-diagnostic-unused-function]
  172 | static inline const metadata& ocsf_redpanda_metadata_cloud_profile() {
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>