serde: fix unused variable warning
Error while processing /home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/165/execroot/_main/src/v/serde/envelope.h.
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/165/execroot/_main/src/v/serde/envelope.h:97:30: error: unused variable 'checksum_envelope_header_size' [clang-diagnostic-unused-const-variable]
   97 | static constexpr std::size_t checksum_envelope_header_size

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>