datalake: fix unused variable warning
Error while processing /home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/41/execroot/_main/src/v/datalake/protobuf_utils.h.
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/41/execroot/_main/src/v/datalake/protobuf_utils.h:18:22: error: unused variable 'max_recursion_depth' [clang-diagnostic-unused-const-variable]
   18 | static constexpr int max_recursion_depth = 100;

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>