redpandan/application: use IsDefined() to check "redpanda" option
since yaml-cpp v0.7.0, YAML::Node cannot be converted to an
"unspecified_bool_type" anymore, instead it now has an
"explicit operator bool() const", see
https://github.com/jbeder/yaml-cpp/commit/848091124d116a110b66247d5c72a2f401ab2446.
so let's use IsDefined() instead for checking the existence of the
"redpanda" node in YAML configuration.

this error is identified with following FTBFS error:

ccache /usr/bin/clang++-15 -DBOOST_ASIO_HAS_STD_INVOKE_RESULT -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_TYPE_ERASE_MORE -DXXH_PRIVATE_API -DZSTD_STATIC_LINKING_ONLY -I/home/kefu/dev/redpanda/src/v -I/home/kefu/dev/redpanda/build/src/v -isystem /home/kefu/dev/redpanda/build/deps_install/include -isystem /home/kefu/dev/redpanda/build/deps_install/include/hdr -fPIC -fsanitize=undefined -fsanitize=address -fcolor-diagnostics -g -fPIC -Wall -Wextra -Werror -Wno-missing-field-initializers -std=c++20 -U_FORTIFY_SOURCE -DSEASTAR_SSTRING -Werror=unused-result "-Wno-error=#warnings" -fstack-clash-protection -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -std=c++20 -MD -MT src/v/redpanda/CMakeFiles/v_application.dir/application.cc.o -MF src/v/redpanda/CMakeFiles/v_application.dir/application.cc.o.d -o src/v/redpanda/CMakeFiles/v_application.dir/application.cc.o -c /home/kefu/dev/redpanda/src/v/redpanda/application.cc
/home/kefu/dev/redpanda/src/v/redpanda/application.cc:327:25: error: assigning to 'bool' from incompatible type 'const YAML::Node'
    _redpanda_enabled = config["redpanda"];
                        ^~~~~~~~~~~~~~~~~~

Signed-off-by: Kefu Chai <tchaikov@gmail.com>