admin: log out-of-range value in error reply
for helping request side understand the error better

this issue is identified by clang-15:

ccache /usr/bin/clang++-15 -DBOOST_ASIO_HAS_STD_INVOKE_RESULT -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_TYPE_ERASE_MORE -DXXH_PRIVATE_API -DZSTD_STATIC_LINKING_ONLY -I/home/kefu/dev/redpanda/src/v -I/home/kefu/dev/redpanda/build/src/v -isystem /home/kefu/dev/redpanda/build/deps_install/include -isystem /home/kefu/dev/redpanda/build/deps_install/include/hdr -fPIC -fsanitize=undefined -fsanitize=address -fcolor-diagnostics -g -fPIC -Wall -Wextra -Werror -Wno-missing-field-initializers -std=c++20 -U_FORTIFY_SOURCE -DSEASTAR_SSTRING -Werror=unused-result "-Wno-error=#warnings" -fstack-clash-protection -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -std=c++20 -MD -MT src/v/redpanda/CMakeFiles/v_application.dir/admin_server.cc.o -MF src/v/redpanda/CMakeFiles/v_application.dir/admin_server.cc.o.d -o src/v/redpanda/CMakeFiles/v_application.dir/admin_server.cc.o -c /home/kefu/dev/redpanda/src/v/redpanda/admin_server.cc
/home/kefu/dev/redpanda/src/v/redpanda/admin_server.cc:1036:35: error: variable 'n' set but not used [-Werror,-Wunused-but-set-variable]
                          int64_t n{0};
                                  ^
1 error generated.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>