cluster: fix unused variable,function warnings
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/10580/execroot/_main/src/v/cluster/cluster_uuid.h:20:23: error: unused variable 'cluster_uuid_key' [clang-diagnostic-unused-const-variable]
   20 | constexpr const char* cluster_uuid_key = "cluster_uuid";
      |                       ^~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/10580/execroot/_main/src/v/cluster/cluster_uuid.h:21:39: error: unused variable 'cluster_uuid_key_space' [clang-diagnostic-unused-const-variable]
   21 | constexpr storage::kvstore::key_space cluster_uuid_key_space

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/10979/execroot/_main/src/v/cluster/commands.h:96:25: error: unused variable 'create_non_replicable_topic_cmd_type' [clang-diagnostic-unused-const-variable]
   96 | static constexpr int8_t create_non_replicable_topic_cmd_type = 6;

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/11273/execroot/_main/src/v/cluster/controller_stm.h:102:31: error: unused variable 'controller_stm_shard' [clang-diagnostic-unused-const-variable]
  102 | static constexpr ss::shard_id controller_stm_shard = 0;

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/11561/execroot/_main/src/v/cluster/health_monitor_types.h:36:31: error: unused variable 'health_monitor_backend_shard' [clang-diagnostic-unused-const-variable]
   36 | static constexpr ss::shard_id health_monitor_backend_shard = 0;

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/12282/execroot/_main/src/v/cluster/prefix_truncate_record.h:22:26: error: unused variable 'prefix_truncate_key' [clang-diagnostic-unused-const-variable]
   22 | static constexpr uint8_t prefix_truncate_key = 0;

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/13997/execroot/_main/src/v/cluster/rm_stm_types.h:18:31: error: unused variable 'abort_snapshot_version' [clang-diagnostic-unused-const-variable]
   18 | static constexpr const int8_t abort_snapshot_version = 0;
      |                               ^~~~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/13997/execroot/_main/src/v/cluster/rm_stm_types.h:19:25: error: unused variable 'prepare_control_record_version' [clang-diagnostic-unused-const-variable]
   19 | static constexpr int8_t prepare_control_record_version{0};
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/13997/execroot/_main/src/v/cluster/rm_stm_types.h:20:25: error: unused variable 'fence_control_record_v0_version' [clang-diagnostic-unused-const-variable]
   20 | static constexpr int8_t fence_control_record_v0_version{0};
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/13997/execroot/_main/src/v/cluster/rm_stm_types.h:21:25: error: unused variable 'fence_control_record_v1_version' [clang-diagnostic-unused-const-variable]
   21 | static constexpr int8_t fence_control_record_v1_version{1};
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/13997/execroot/_main/src/v/cluster/rm_stm_types.h:22:25: error: unused variable 'fence_control_record_version' [clang-diagnostic-unused-const-variable]
   22 | static constexpr int8_t fence_control_record_version{2};
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/14429/execroot/_main/src/v/cluster/raft0_utils.h:24:34: error: unused function 'create_raft0' [clang-diagnostic-unused-function]
   24 | static ss::future<consensus_ptr> create_raft0(

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/15018/execroot/_main/src/v/cluster/scheduling/constraints.h:25:35: error: unused variable 'rack_label' [clang-diagnostic-unused-const-variable]
   25 | static constexpr std::string_view rack_label = "rack";

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>