features: fix unused variable warning
Error while processing /home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1219/execroot/_main/src/v/features/feature_table.h.
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1219/execroot/_main/src/v/features/feature_table.h:220:29: error: unused variable 'feature_schema' [clang-diagnostic-unused-const-variable]
  220 | constexpr static std::array feature_schema{

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>