cloud_storage: print exception pointer instead of a function pointer
* use std::current_exception() instead of std::current_exception, for
  retrieving current exception. the later is a function

otherwise we'd have following FTBFS:

FAILED: src/v/cloud_storage/CMakeFiles/v_cloud_storage.dir/remote_partition.cc.o
ccache /usr/bin/clang++-15 -DBOOST_ASIO_HAS_STD_INVOKE_RESULT -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_TYPE_ERASE_MORE -DXXH_PRIVATE_API -DZSTD_STATIC_LINKING_ONLY -I/home/kefu/dev/redpanda/src/v -I/home/kefu/dev/redpanda/build/src/v -isystem /home/kefu/dev/redpanda/build/deps_install/include -isystem /home/kefu/dev/redpanda/build/deps_install/include/hdr -fPIC -fsanitize=undefined -fsanitize=address -fcolor-diagnostics -g -fPIC -Wall -Wextra -Werror -Wno-missing-field-initializers -std=c++20 -U_FORTIFY_SOURCE -DSEASTAR_SSTRING -Werror=unused-result "-Wno-error=#warnings" -fstack-clash-protection -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -std=c++20 -MD -MT src/v/cloud_storage/CMakeFiles/v_cloud_storage.dir/remote_partition.cc.o -MF src/v/cloud_storage/CMakeFiles/v_cloud_storage.dir/remote_partition.cc.o.d -o src/v/cloud_storage/CMakeFiles/v_cloud_storage.dir/remote_partition.cc.o -c /home/kefu/dev/redpanda/src/v/cloud_storage/remote_partition.cc
In file included from /home/kefu/dev/redpanda/src/v/cloud_storage/remote_partition.cc:11:
In file included from /home/kefu/dev/redpanda/src/v/cloud_storage/remote_partition.h:13:
In file included from /home/kefu/dev/redpanda/src/v/cloud_storage/offset_translation_layer.h:13:
In file included from /home/kefu/dev/redpanda/src/v/cloud_storage/partition_manifest.h:13:
In file included from /home/kefu/dev/redpanda/src/v/cloud_storage/base_manifest.h:13:
In file included from /home/kefu/dev/redpanda/src/v/cloud_storage/types.h:13:
In file included from /home/kefu/dev/redpanda/src/v/s3/client.h:13:
In file included from /home/kefu/dev/redpanda/src/v/http/client.h:14:
In file included from /home/kefu/dev/redpanda/src/v/bytes/details/io_fragment.h:14:
In file included from /home/kefu/dev/redpanda/src/v/bytes/details/out_of_range.h:15:
In file included from /home/kefu/dev/redpanda/build/deps_install/include/fmt/format.h:48:
/home/kefu/dev/redpanda/build/deps_install/include/fmt/core.h:1722:3: error: static_assert failed due to requirement 'formattable_pointer' "Formatting of non-void pointers is disallowed."
  static_assert(formattable_pointer,
  ^             ~~~~~~~~~~~~~~~~~~~
/home/kefu/dev/redpanda/build/deps_install/include/fmt/core.h:1853:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::basic_format_context<fmt::appender, char>, fmt::detail::type::custom_type, std::__exception_ptr::exception_ptr (&)() noexcept, 0>' requested here
        data_{detail::make_arg<
                      ^
/home/kefu/dev/redpanda/build/deps_install/include/fmt/core.h:1872:10: note: in instantiation of function template specialization 'fmt::format_arg_store<fmt::basic_format_context<fmt::appender, char>, const char *, int, std::__exception_ptr::exception_ptr () noexcept>::format_arg_store<const char *&, int &, std::__exception_ptr::exception_ptr (&)() noexcept>' requested here
  return {std::forward<Args>(args)...};
         ^
/home/kefu/dev/redpanda/build/deps_install/include/fmt/core.h:3188:50: note: in instantiation of function template specialization 'fmt::make_format_args<fmt::basic_format_context<fmt::appender, char>, const char *&, int &, std::__exception_ptr::exception_ptr (&)() noexcept>' requested here
  detail::vformat_to(buf, string_view(fmt), fmt::make_format_args(args...), {});
                                                 ^
/home/kefu/dev/redpanda/src/v/ssx/sformat.h:48:22: note: in instantiation of function template specialization 'fmt::formatted_size<const char *, int, std::__exception_ptr::exception_ptr (&)() noexcept>' requested here
    auto size = fmt::formatted_size(format_str, std::forward<Args>(args)...);
                     ^
/home/kefu/dev/redpanda/src/v/utils/retry_chain_node.h:367:33: note: in instantiation of function template specialization 'ssx::sformat<const char *, int, std::__exception_ptr::exception_ptr (&)() noexcept>' requested here
                auto msg = ssx::sformat(format, std::forward<Args>(args)...);
                                ^
/home/kefu/dev/redpanda/src/v/utils/retry_chain_node.h:383:9: note: in instantiation of function template specialization 'retry_chain_logger::log<const char *, int, std::__exception_ptr::exception_ptr (&)() noexcept>' requested here
        log(ss::log_level::error, format, std::forward<Args>(args)...);
        ^
/home/kefu/dev/redpanda/src/v/cloud_storage/remote_partition.cc:119:27: note: in instantiation of function template specialization 'retry_chain_logger::error<const char *, int, std::__exception_ptr::exception_ptr (&)() noexcept>' requested here
                  _ctxlog.error,
                          ^

Signed-off-by: Kefu Chai <tchaikov@gmail.com>