cloud_roles: fix unused return value warning
/home/nwatkins/src/redpanda-clang-18/src/v/cloud_roles/tests/credential_tests.cc:89:9: error: the value returned by this function should not be disregarded; neglecting it may lead to errors [bugprone-unused-return-value,-warnings-as-errors]
   89 |         applier.add_auth(h);
      |         ^~~~~~~~~~~~~~~~~~~
/home/nwatkins/src/redpanda-clang-18/src/v/cloud_roles/tests/credential_tests.cc:99:9: error: the value returned by this function should not be disregarded; neglecting it may lead to errors [bugprone-unused-return-value,-warnings-as-errors]
   99 |         applier.add_auth(h);
      |         ^~~~~~~~~~~~~~~~~~~

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>