wasm: fix unused variable warnings
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1435/execroot/_main/src/v/wasm/wasi.h:65:28: error: unused variable 'preview_1_start_function_name' [clang-diagnostic-unused-const-variable]
   65 | constexpr std::string_view preview_1_start_function_name = "_start";
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1435/execroot/_main/src/v/wasm/wasi.h:69:19: error: unused variable 'ERRNO_SUCCESS' [clang-diagnostic-unused-const-variable]
   69 | constexpr errno_t ERRNO_SUCCESS{0};
      |                   ^~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1435/execroot/_main/src/v/wasm/wasi.h:70:19: error: unused variable 'ERRNO_INVAL' [clang-diagnostic-unused-const-variable]
   70 | constexpr errno_t ERRNO_INVAL{16};
      |                   ^~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1435/execroot/_main/src/v/wasm/wasi.h:71:19: error: unused variable 'ERRNO_NOSYS' [clang-diagnostic-unused-const-variable]
   71 | constexpr errno_t ERRNO_NOSYS{52};
      |                   ^~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1435/execroot/_main/src/v/wasm/wasi.h:72:19: error: unused variable 'ERRNO_BADF' [clang-diagnostic-unused-const-variable]
   72 | constexpr errno_t ERRNO_BADF{8};
      |                   ^~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1435/execroot/_main/src/v/wasm/wasi.h:76:22: error: unused variable 'REALTIME_CLOCK_ID' [clang-diagnostic-unused-const-variable]
   76 | constexpr clock_id_t REALTIME_CLOCK_ID{0};
      |                      ^~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1435/execroot/_main/src/v/wasm/wasi.h:77:22: error: unused variable 'MONOTONIC_CLOCK_ID' [clang-diagnostic-unused-const-variable]
   77 | constexpr clock_id_t MONOTONIC_CLOCK_ID{1};
      |                      ^~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1435/execroot/_main/src/v/wasm/wasi.h:78:22: error: unused variable 'PROCESS_CPUTIME_CLOCK_ID' [clang-diagnostic-unused-const-variable]
   78 | constexpr clock_id_t PROCESS_CPUTIME_CLOCK_ID{2};
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1435/execroot/_main/src/v/wasm/wasi.h:79:22: error: unused variable 'THREAD_CPUTIME_CLOCK_ID' [clang-diagnostic-unused-const-variable]
   79 | constexpr clock_id_t THREAD_CPUTIME_CLOCK_ID{3};
      |                      ^~~~~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1435/execroot/_main/src/v/wasm/wasi.h:92:24: error: unused variable 'CLOCK_EVENT_TYPE' [clang-diagnostic-unused-const-variable]
   92 | constexpr event_type_t CLOCK_EVENT_TYPE{0};
      |                        ^~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1435/execroot/_main/src/v/wasm/wasi.h:97:24: error: unused variable 'FD_READ_EVENT_TYPE' [clang-diagnostic-unused-const-variable]
   97 | constexpr event_type_t FD_READ_EVENT_TYPE{1};
      |                        ^~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1435/execroot/_main/src/v/wasm/wasi.h:102:24: error: unused variable 'FD_WRITE_EVENT_TYPE' [clang-diagnostic-unused-const-variable]
  102 | constexpr event_type_t FD_WRITE_EVENT_TYPE{2};
      |                        ^~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1435/execroot/_main/src/v/wasm/wasi.h:116:27: error: unused variable 'RELATIVE_TIME_SUBCLOCK_FLAG' [clang-diagnostic-unused-const-variable]
  116 | constexpr subclockflags_t RELATIVE_TIME_SUBCLOCK_FLAG{0};
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1435/execroot/_main/src/v/wasm/wasi.h:117:27: error: unused variable 'ABSOLUTE_TIME_SUBCLOCK_FLAG' [clang-diagnostic-unused-const-variable]
  117 | constexpr subclockflags_t ABSOLUTE_TIME_SUBCLOCK_FLAG{1};

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>