tidy: remove unused namespace aliases
/home/nwatkins/src/redpanda/src/v/cloud_storage_clients/client_probe.cc:36:15: error: namespace alias decl 'sm' is unused [misc-unused-alias-decls,-warnings-as-errors]
    namespace sm = ss::metrics;
    ~~~~~~~~~~^~~~~~~~~~~~~~~~~

/home/nwatkins/src/redpanda/src/v/pandaproxy/rest/test/list_topics.cc:19:11: error: namespace alias decl 'pp' is unused [misc-unused-alias-decls,-warnings-as-errors]
namespace pp = pandaproxy;
~~~~~~~~~~^~~~~~~~~~~~~~~~

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>