raft: fix unused variable warning
Error while processing /home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1607/execroot/_main/src/v/raft/fundamental.h.
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1607/execroot/_main/src/v/raft/fundamental.h:26:41: error: unused variable 'no_timeout' [clang-diagnostic-unused-const-variable]
   26 | static constexpr clock_type::time_point no_timeout

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>