ssx::sformat: do not specify the namespace in the same namespace
this is confusing from compiler and programmer's perspective:
what if `fmt` namespace has a nested `fmt` namespace?

GCC-12 complains like

error: extra qualification 'fmt::' on member 'formatter'

so, in this change `fmt::formatter` is moved out of the `fmt`
namespace.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>