storage: fix missing header
ir/mem_log_impl.cc.o -c ../../../src/v/storage/mem_log_impl.cc
../../../src/v/storage/mem_log_impl.cc:304:13: error: reference to non-static member function must be called
      stlog.trace,
      ~~~~~~^~~~~
v_deps_install/include/seastar/util/log.hh:191:10: note: possible target for call
    void trace(const char* fmt, Args&&... args) {
         ^

Signed-off-by: Noah Watkins <noah@vectorized.io>