kafka/protocol/schemata: define default operator==() if possible
* generator.py: add default-generated operator==() to types which can
  have default-generated operator==(). for those who contains
  non-generated types which cannot have default-generated opereator==(),
  they are listed in WITHOUT_DEFAULT_EQUALITY_OPERATOR. so far, only
  `produce_request_record_data` and `batch_reader` are in the list. because:
  - they are not generated using the generator.py script, so the generator.py
    cannot deduce if it is eligible to have the default-generated
    operator==().
  - they have iobuf as its indirect member variable via `kafka_batch_adapter`.
    and iobuf is not default-comparable.
  - we have dedicated rule in generator.py to synthesis a type
    definition which contains either of these types.
  this helps to eliminate the handcrafted 'operator==()' implementations,
  - better maintanability
  - easier to compiler to find the used operator==() if it needs them.
* use default generated operator==() when appropriate.
  simpler this way. also, this helps the compiler to see the comparison
  operators before they are used.

this change helps to address the FTBFS with clang++-15 + libstd++-12:

/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_algobase.h:1161:22: error: invalid operands to binary expression ('const kafka::api_versions_response_key' and 'const kafka::api_versions_response_key')
            if (!(*__first1 == *__first2))
                  ~~~~~~~~~ ^  ~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_algobase.h:1210:38: note: in instantiation of function template specialization 'std::__equal<false>::equal<const kafka::api_versions_response_key *, const kafka::api_versions_response_key *>' requested here
      return std::__equal<__simple>::equal(__first1, __last1, __first2);
                                     ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_algobase.h:1218:19: note: in instantiation of function template specialization 'std::__equal_aux1<const kafka::api_versions_response_key *, const kafka::api_versions_response_key *>' requested here
      return std::__equal_aux1(std::__niter_base(__first1),
                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_algobase.h:1555:19: note: in instantiation of function template specialization 'std::__equal_aux<__gnu_cxx::__normal_iterator<const kafka::api_versions_response_key *, std::vector<kafka::api_versions_response_key>>, __gnu_cxx::__normal_iterator<const kafka::api_versions_response_key *, std::vector<kafka::api_versions_response_key>>>' requested here
      return std::__equal_aux(__first1, __last1, __first2);
                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:2037:16: note: in instantiation of function template specialization 'std::equal<__gnu_cxx::__normal_iterator<const kafka::api_versions_response_key *, std::vector<kafka::api_versions_response_key>>, __gnu_cxx::__normal_iterator<const kafka::api_versions_response_key *, std::vector<kafka::api_versions_response_key>>>' requested here
              && std::equal(__x.begin(), __x.end(), __y.begin())); }
                      ^
/home/kefu/dev/redpanda/src/v/kafka/protocol/api_versions.h:67:35: note: in instantiation of function template specialization 'std::operator==<kafka::api_versions_response_key, std::allocator<kafka::api_versions_response_key>>' requested here
               && a.data.api_keys == b.data.api_keys
                                  ^
/home/kefu/dev/redpanda/src/v/kafka/protocol/join_group.h:137:13: note: candidate function not viable: no known conversion from 'const kafka::api_versions_response_key' to 'const std::vector<join_group_request_protocol>' for 1st argument
inline bool operator==(
            ^

Signed-off-by: Kefu Chai <tchaikov@gmail.com>