cloud_storage: fix unused variable,function warning
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1752/execroot/_main/src/v/cloud_storage_clients/client_pool.h:36:24: error: unused variable 'self_config_shard' [clang-diagnostic-unused-const-variable]
   36 | constexpr ss::shard_id self_config_shard = ss::shard_id{0};
      |                        ^~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/2577/execroot/_main/src/v/cloud_storage/recursive_directory_walker.h:23:16: error: unused variable 'cache_tmp_file_extension' [clang-diagnostic-unused-const-variable]
   23 | constexpr auto cache_tmp_file_extension{".part"};

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/8954/execroot/_main/src/v/cloud_storage/tests/common_def.h:36:19: error: unused variable 'archiver_term' [clang-diagnostic-unused-const-variable]
   36 | static const auto archiver_term = model::term_id{123};
      |                   ^~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/9899/execroot/_main/src/v/cloud_storage/cache_service.h:43:41: error: unused variable 'cache_hydration_timeout' [clang-diagnostic-unused-const-variable]
   43 | static const ss::lowres_clock::duration cache_hydration_timeout = 60s;
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/9899/execroot/_main/src/v/cloud_storage/cache_service.h:44:41: error: unused variable 'cache_hydration_backoff' [clang-diagnostic-unused-const-variable]
   44 | static const ss::lowres_clock::duration cache_hydration_backoff = 250ms;
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/9899/execroot/_main/src/v/cloud_storage/cache_service.h:48:41: error: unused variable 'cache_thrash_backoff' [clang-diagnostic-unused-const-variable]
   48 | static const ss::lowres_clock::duration cache_thrash_backoff = 5000ms;
      |                                         ^~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/10015/execroot/_main/src/v/cloud_storage/remote.h:45:31: error: unused variable 'auth_refresh_shard_id' [clang-diagnostic-unused-const-variable]
   45 | static constexpr ss::shard_id auth_refresh_shard_id = 0;
      |                               ^~~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/10185/execroot/_main/src/v/cloud_storage/segment_meta_cstore.h:33:18: error: unused variable 'cstore_sampling_rate' [clang-diagnostic-unused-const-variable]
   33 | constexpr size_t cstore_sampling_rate = 8;
      |                  ^~~~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/137/execroot/_main/src/v/cloud_storage/remote_segment.h:43:25: error: unused variable 'remote_segment_sampling_step_bytes' [clang-diagnostic-unused-const-variable]
   43 | static constexpr size_t remote_segment_sampling_step_bytes = 64_KiB;

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>