serde: fix unused variable warning
Error while processing /home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/480/execroot/_main/src/v/serde/rw/chrono.h.
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/480/execroot/_main/src/v/serde/rw/chrono.h:20:16: error: unused variable 'max_serializable_ms' [clang-diagnostic-unused-const-variable]
   20 | constexpr auto max_serializable_ms

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>