storage: fix unused function warnings
Error while processing /home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1987/execroot/_main/src/v/storage/tests/utils/disk_log_builder.h.
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1987/execroot/_main/src/v/storage/tests/utils/disk_log_builder.h:40:26: error: function 'log_builder_config' is not needed and will not be emitted [clang-diagnostic-unneeded-internal-declaration]
   40 | static inline log_config log_builder_config() {
      |                          ^~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1987/execroot/_main/src/v/storage/tests/utils/disk_log_builder.h:48:33: error: function 'reader_config' is not needed and will not be emitted [clang-diagnostic-unneeded-internal-declaration]
48 | static inline log_reader_config reader_config() {
      |                                 ^~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1987/execroot/_main/src/v/storage/tests/utils/disk_log_builder.h:55:33: error: function 'append_config' is not needed and will not be emitted [clang-diagnostic-unneeded-internal-declaration]
   55 | static inline log_append_config append_config() {
      |                                 ^~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1987/execroot/_main/src/v/storage/tests/utils/disk_log_builder.h:62:26: error: function 'log_builder_ntp' is not needed and will not be emitted [clang-diagnostic-unneeded-internal-declaration]
   62 | static inline model::ntp log_builder_ntp() {
      |                          ^~~~~~~~~~~~~~~

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>