utils: fix fragmented vector with libstdc++
[6/699] Building CXX object src/v/utils/tests/CMakeFiles/utils_unit_rpunit.dir/fragmented_vector_test.cc.o
FAILED: src/v/utils/tests/CMakeFiles/utils_unit_rpunit.dir/fragmented_vector_test.cc.o
/usr/include/c++/11/bits/stl_algobase.h:1499:32:   required from 'constexpr _ForwardIterator
   std::lower_bound(_ForwardIterator, _ForwardIterator, const _Tp&) [with _ForwardIterator = fragmented_vector<long int, 1024>::const_iterator; _Tp = long int]'
../src/v/utils/tests/fragmented_vector_test.cc:74:36:   required from here
/usr/include/c++/11/bits/stl_iterator_base_funcs.h:183:9: error: no match for 'operator--' (operand type is 'fragmented_vector<long int, 1024>::const_iterator')
  183 |         --__i;
      |         ^~~~~

Signed-off-by: Noah Watkins <noah@vectorized.io>