cluster: fix unused constexpr variable
constexpr doesn't imply inline for variables.

Error while processing /home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/6098/execroot/_main/src/v/cluster/notification.h.
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/6098/execroot/_main/src/v/cluster/notification.h:19:32: error: unused variable 'notification_id_type_invalid' [clang-diagnostic-unused-const-variable]
   19 | constexpr notification_id_type notification_id_type_invalid{-1};

Error while processing /home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/6167/execroot/_main/src/v/cluster/version.h.
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/6167/execroot/_main/src/v/cluster/version.h:22:27: error: unused variable 'invalid_version' [clang-diagnostic-unused-const-variable]
   22 | constexpr cluster_version invalid_version = cluster_version{-1};

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>