storage: add missing flush in a test
This fails spuriously because the test doesn't use batch cache and data
doesn't necessarily get to the disk by the time we read it as writes are
asynchronous.

```
fatal error: in "reader_reusability_test_parser_header": critical check rec.size() == 1 has failed [0 != 1]`
```