c/md_dissemination: do not capture unused variable
req is not used in the continuation, neither is it holding a resource
which we should keep alive. so let's just drop it.

/home/kefu/dev/redpanda/src/v/cluster/metadata_dissemination_handler.cc:105:38: error: lambda capture 'req' is not used [-Werror,-Wunused-lambda-capture]
      get_scheduling_group(), [this, req = std::move(req)]() mutable {
                                   ~~^~~~~~~~~~~~~~~~~~~~
1 error generated.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>