debug_bundle: fix unused variable warning
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/8713/execroot/_main/src/v/debug_bundle/types.h:35:31: error: unused variable 'service_shard' [clang-diagnostic-unused-const-variable]
   35 | static constexpr ss::shard_id service_shard = 0;
      |                               ^~~~~~~~~~~~~

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>