features: remove cluster/types.h inclusion
Feature table is included all over the tree, yet it included
cluster/types.h which has a large number of other dependencies. Feature
table only needs the cluster_version definition. In affect feature table
was being used around the tree as an implicit alias for cluster/types.h.

  In file included from src/v/storage/segment_reader.cc:16:
  In file included from src/v/storage/segment_utils.h:20:
  In file included from src/v/storage/readers_cache.h:20:
  In file included from src/v/storage/log_reader.h:20:
  In file included from src/v/storage/segment.h:20:
  In file included from src/v/storage/segment_index.h:13:
  In file included from src/v/features/feature_table.h:14:
  In file included from src/v/cluster/types.h:14:
  In file included from src/v/cluster/cloud_metadata/cluster_manifest.h:13:
  In file included from src/v/cloud_storage/base_manifest.h:14:
  In file included from src/v/cloud_storage/types.h:14:
  In file included from src/v/cloud_storage_clients/configuration.h:14:
  src/redpanda-storage-v2/src/v/cloud_storage_clients/client_probe.h:17:10: fatal error: 'http/probe.h' file not found
  #include "http/probe.h"

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>