[CORE-14506] rptest: limit duck_db test to S3
Our duckdb query service requires S3 (presumably it just needs more work
on our end):

```
AssertionError: DuckDBPy query service is implemented only for S3 credentials
```