raft: fix unused variable warning
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/2385/execroot/_main/src/v/raft/tests/raft_fixture.h:42:33: error: unused variable 'test_group' [clang-diagnostic-unused-const-variable]
   42 | static constexpr raft::group_id test_group(123);

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/9068/execroot/_main/src/v/raft/types.h:727:33: error: unused variable 'zero_voter_priority' [clang-diagnostic-unused-const-variable]
  727 | static constexpr voter_priority zero_voter_priority = voter_priority{0};

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/9068/execroot/_main/src/v/raft/types.h:729:33: error: unused variable 'min_voter_priority' [clang-diagnostic-unused-const-variable]
  729 | static constexpr voter_priority min_voter_priority = voter_priority{1};

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/9145/execroot/_main/src/v/raft/persisted_stm.h:28:31: error: unused variable 'stm_snapshot_version_v0' [clang-diagnostic-unused-const-variable]
   28 | static constexpr const int8_t stm_snapshot_version_v0 = 0;

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/9145/execroot/_main/src/v/raft/persisted_stm.h:29:31: error: unused variable 'stm_snapshot_version' [clang-diagnostic-unused-const-variable]
   29 | static constexpr const int8_t stm_snapshot_version = 1;

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/9498/execroot/_main/src/v/raft/group_configuration.h:29:37: error: unused variable 'no_revision' [clang-diagnostic-unused-const-variable]
   29 | static constexpr model::revision_id no_revision{};

/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/9625/execroot/_main/src/v/raft/notification.h:19:41: error: unused variable 'notification_id_type_invalid' [clang-diagnostic-unused-const-variable]
   19 | constexpr group_manager_notification_id notification_id_type_invalid{-1};

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>