dt/redpanda: Mitigate a race during render
Avoid `AttributeError: 'RedpandaService' object has no attribute 'template_env'`
by waiting for `template_env` if `template_loader` has been set.

https://github.com/confluentinc/ducktape/blob/v0.8.8/ducktape/template.py#L67-L95

Fix redpanda-data#6944

Signed-off-by: Ben Pope <ben@redpanda.com>