iceberg: serialize empty 'partitions' as empty array
Redshift complains when using an null 'partitions' field in the manifest
list:

```
ERROR: Wrong type in Avro file. Detail: ----------------------------------------------- error: Wrong type in Avro file. code: 15003 context: Field: partitions. Expected: 12. Got: 7 query: -1[child_sequence:1] location: avro_utils.hpp:55 process: padbmaster [pid=1073913955] ----------------------------------------------- [ErrorId: 1-68963282-20644b700a198f806702f6aa]
```

This fix has Redpanda serialize empty 'partitions' as an empty array.
Tested manually against Glue and Redshift.

(cherry picked from commit 61c9992d3023598e8249c1bd2060c68ecbf21aa8)