tidy: fix moves of trivially copyable types
/home/nwatkins/src/redpanda/src/v/cluster/node_status_table.h:47:50: error: std::move of the variable 'node_status' of the trivially-copyable type 'cluster::node_status' has no effect; remove std::move() [performance-move-const-arg,-warnings-as-errors]
            _peers_status[node_status.node_id] = std::move(node_status);
                                                 ^~~~~~~~~~           ~

/home/nwatkins/src/redpanda/src/v/raft/vote_stm.h:61:58: error: std::move of the variable 'r' of the trivially-copyable type 'result<vote_reply>' (aka 'basic_result<raft::vote_reply, std::error_code, boost::outcome_v2::policy::error_code_throw_as_system_error<raft::vote_reply, std::error_code, void>>') has no effect; remove std::move() [performance-move-const-arg,-warnings-as-err
ors]
            value = std::make_unique<result<vote_reply>>(std::move(r));
                                                         ^~~~~~~~~~ ~

/home/nwatkins/src/redpanda/src/v/rpc/transport.cc:39:12: error: std::move of the variable 'h' of the trivially-copyable type 'header' has no effect; remove std::move() [performance-move-const-arg,-warnings-as-errors]
      , _h(std::move(h)) {}
           ^~~~~~~~~~ ~
/home/nwatkins/src/redpanda/src/v/rpc/transport.cc:383:31: error: std::move of the expression of the trivially-copyable type 'value_type' (aka 'rpc::header') has no effect; remove std::move() [performance-move-const-arg,-warnings-as-errors]
              return dispatch(std::move(h.value()));
                              ^~~~~~~~~~         ~

/home/nwatkins/src/redpanda/src/v/rpc/netbuf.cc:33:16: error: std::move of the expression of the trivially-copyable type 'header' has no effect; remove std::move() [performance-move-const-arg,-warnings-as-errors]
    auto hdr = std::move(_hdr);
               ^~~~~~~~~~    ~

/home/nwatkins/src/redpanda/src/v/net/connection.cc:129:25: error: std::move of the variable 'in_config' of the trivially-copyable type 'ss::connected_socket_input_stream_config' has no effect; remove std::move() [performance-move-const-arg,-warnings-as-errors]
        _in = _fd.input(std::move(in_config));
                        ^~~~~~~~~~         ~

/home/nwatkins/src/redpanda/src/v/security/acl.h:433:15: error: std::move of the variable 'host' of the trivially-copyable type 'std::optional<acl_host>' has no effect; remove std::move() [performance-move-const-arg,-warnings-as-errors]
      , _host(std::move(host))
              ^~~~~~~~~~    ~

/home/nwatkins/src/redpanda/src/v/storage/fs_utils.h:130:19: error: std::move of the variable 'file_part' of the trivially-copyable type 'segment_path::metadata' has no effect; remove std::move() [performance-move-const-arg,-warnings-as-errors]
      , file_part(std::move(file_part)) {}
                  ^~~~~~~~~~         ~

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>