crypto: fix unused variable warning
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/422/execroot/_main/src/v/crypto/tests/test_values.h:19:35: error: unused variable 'md5_test_val' [clang-diagnostic-unused-const-variable]
   19 | static constexpr std::string_view md5_test_val

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>