tools: fix rp-storage-tool github action
The action-rs plugin doesn't support the working-directory syntax we
were trying to use. This commit fixes the hook by using a workaround[1].

We would previously see errors like this in CI:

Warning: Unexpected input(s) 'working-directory', valid inputs are ['command', 'toolchain', 'args', 'use-cross']
Run actions-rs/cargo@v1
/home/runner/.cargo/bin/cargo test
error: could not find `Cargo.toml` in `/home/runner/work/redpanda/redpanda` or any parent directory
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101

[1] https://github.com/actions-rs/cargo/issues/6#issuecomment-567368244