hashing: fix unused function warning
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/5455/execroot/_main/src/v/hashing/jump_consistent_hash.h:19:1: error: unused function 'jump_consistent_hash' [clang-diagnostic-unused-function]
   19 | jump_consistent_hash(uint64_t key, uint32_t num_buckets) {

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>