bazel: Apply Wno-backend-plugin to abseil crc_x86_arm_combined.cc
We were seeing:

```
error: external/abseil-cpp+/absl/crc/internal/crc_x86_arm_combined.cc: Function _ZNK4absl12lts_2025081412crc_internal12_GLOBAL__N_145CRC32AcceleratedX86ARMCombinedMultipleStreamsILm1ELm2ELNS2_14CutoffStrategyE1EE6ExtendEPjPKvm is annotated as a hot function but the profile is cold [-Werror,-Wbackend-plugin]
```

`CRC32AcceleratedX86ARMCombinedMultipleStreams::Extend` is marked
`__hot__`.

However, it's a template with non-type template parameters which are
chosen based on the host CPU type.

In training naturally only ever one of those instantiations gets trained
on. The others stay cold.

LLVM emits a warning when a function marked `__hot__` has cold profile
data.

With our new -Werror in external files this caused a build failure.
Silence the warning in that file to fix the build.