rpc: assert() only if output type support both dencoders
* conditionally assert on equality between the version used to encode the output
  and version set by the request's header
* update the comment to reflect the precondition based on which we have
  this assert
* the `std::ignore` statements are added to silence warnings like:

  ../src/v/rpc/service.h:88:30: error: lambda capture 'version' is not used [-Werror,-Wunused-lambda-capture]
                        .then([version, b = std::move(b)](
                               ^

this change addresses following test failure from `coproc_fixture_unstable_rpunit`:

ERROR 2022-07-24 14:46:15,560 [shard 0] assert - Assert failure: (../src/v/rpc/service.h:98) 'effective_version == version' auto rpc::service::execution_helper<detail::base_named_type<signed char, coproc::empty_req_tag, std::integral_constant<bool, true>>, coproc::disable_copros_reply, rpc::default_message_codec>::exec(ss::input_stream<char> &, rpc::streaming_context &, uint32_t, (lambda at src/v/coproc/supervisor.h:204:7) &&)::(anonymous class)::operator()()::(anonymous class)::operator()(coproc::disable_copros_reply)::(anonymous class)::operator()(rpc::transport_version) const [Input = detail::base_named_type<signed char, coproc::empty_req_tag, std::integral_constant<bool, true>>, Output = coproc::disable_copros_reply, Codec = rpc::default_message_codec]: Unexpected encoding at effective rpc::transport_version::v0 != rpc::transport_version::v2

in which, `Codec` is `default_message_codec`, `Output`'s type is
`coproc::disable_copros_reply`, which marks itself exempt from the
serde dencoder. `Input` is `coproc::empty_request`. the type
of `Output` is just another part of the RPC method, so `parse_type()` is
not able to determine/check the output's type. hence we cannot assume
the equality between these two versions. the assertion is safe only when
the `output` type is versatile enough to support both encodings, so that
is is able use the given version.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>