Eagerly list all files in compute_storage.py
Listing the segments lazily means that our try..catch wrapper does
nothing.

Fixes errors like seen here: https://ci-artifacts.dev.vectorized.cloud/redpanda/35662/018a299c-8e38-43c8-b545-edb4c4375eb6/vbuild/ducktape/results/2023-08-24--001/TopicDeleteStressTest/stress_test/193/report.txt

Stack trace below:

```
ducktape.cluster.remoteaccount.RemoteCommandError: root@docker-rp-14: Command 'python3 /tmp/compute_storage.py --data-dir=/var/lib/redpanda/data' returned non-zero exit status 1. Remote error message: b'Traceback (most recent call last):\n  File "/tmp/compute_storage.py", line 78, in <module>\n    output = compute_size(data_dir, args.sizes)\n  File "/tmp/compute_storage.py", line 49, in compute_size\n    for segment in safe_listdir(partition):\n  File "/usr/lib/python3.10/pathlib.py", line 1017, in iterdir\n    for name in self._accessor.listdir(self):\nFileNotFoundError: [Errno 2] No such file or directory: \'/var/lib/redpanda/data/kafka/topic-yogwctkfkk/0_28\'\n'
```

Signed-off-by: Tyler Rockwood <rockwood@redpanda.com>
(cherry picked from commit 7dbfffc709aedafd9be319d46dea3a18d425839e)