random: fix unused variable warnings
Error while processing /home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1559/execroot/_main/src/v/random/generators.h.
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1559/execroot/_main/src/v/random/generators.h:36:48: error: variable 'secure_private_rng' is not needed and will not be emitted [clang-diagnostic-unneeded-internal-declaration]
   36 | static thread_local crypto::secure_private_rng secure_private_rng{};
      |                                                ^~~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1559/execroot/_main/src/v/random/generators.h:37:47: error: variable 'secure_public_rng' is not needed and will not be emitted [clang-diagnostic-unneeded-internal-declaration]
   37 | static thread_local crypto::secure_public_rng secure_public_rng{};
      |                                               ^~~~~~~~~~~~~~~~~
/home/nwatkins/.cache/bazel/_bazel_nwatkins/31f1aa7012681f681e8d49a1818a8564/sandbox/linux-sandbox/1559/execroot/_main/src/v/random/generators.h:47:25: error: unused variable 'alphanum_max_distinct_strlen' [clang-diagnostic-unused-const-variable]
   47 | static constexpr size_t alphanum_max_distinct_strlen = 32;

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>